---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbmaster
  labels:
    app: bc-test
    name: dbmaster
  annotations:
    volume.alpha.kubernetes.io/storage-class: generic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi